from django.contrib import admin
from django.urls import path

from crudapp import views

urlpatterns = [
    path('empregister', views.emp, name= 'Employee Register'),
    path('show', views.show, name= 'show'),
    path('delete/<int:id>', views.destroy), # <int:id> is id which is django autogenerated primary key of model has to be int so url will be ex: delete/12
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    ]