# Generated by Django 2.1.5 on 2020-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
