# Generated by Django 2.1.5 on 2020-05-11 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
