# Generated by Django 2.1.5 on 2020-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NA', 'Not Applicable')], default='NA', max_length=1),
        ),
    ]
