# Generated by Django 3.1.2 on 2020-10-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NA', 'Not Applicable')], default='NA', max_length=10),
        ),
    ]
